package com.vhg.patientmonitoring.model.alert;


import com.vhg.patientmonitoring.model.reading.VitalSignReading;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Represents an alert generated by the system
 */
public class Alert {
    private String alertId;
    private String patientId;
    private AlertSeverity severity;
    private String message;
    private LocalDateTime timestamp;
    private AlertStatus status;
    private VitalSignReading triggeringReading;

    // Constructor, getters, setters

    public Alert(String patientId, AlertSeverity severity, String message, VitalSignReading triggeringReading) {
        this.alertId = UUID.randomUUID().toString();
        this.patientId = patientId;
        this.severity = severity;
        this.message = message;
        this.timestamp = LocalDateTime.now();
        this.status = AlertStatus.PENDING;
        this.triggeringReading = triggeringReading;
    }

    public AlertSeverity getSeverity() {
        return this.severity;
    }
}